spring.application.name=plataforma_servicios
server.port=8080

# Dirección de la Base de Datos apuntando a tu phpMyAdmin
spring.datasource.url=jdbc:mysql://localhost:3306/plataforma_servicios?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para creación automática de tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Fuerza el dialecto compatible con el MariaDB de tu XAMPP
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Desactiva las alertas de vista de JPA en consola
spring.jpa.open-in-view=false

# Credenciales temporales de desarrollo para saltar Spring Security
spring.security.user.name=admin
spring.security.user.password=admin